// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: column_references.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const deleteColumnReferencesByIndexRun = `-- name: DeleteColumnReferencesByIndexRun :exec
DELETE FROM column_references WHERE index_run_id = $1
`

func (q *Queries) DeleteColumnReferencesByIndexRun(ctx context.Context, indexRunID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteColumnReferencesByIndexRun, indexRunID)
	return err
}

const insertColumnReference = `-- name: InsertColumnReference :exec
INSERT INTO column_references (project_id, index_run_id, source_column, target_column, derivation_type, expression, context, line)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertColumnReferenceParams struct {
	ProjectID      uuid.UUID `json:"project_id"`
	IndexRunID     uuid.UUID `json:"index_run_id"`
	SourceColumn   string    `json:"source_column"`
	TargetColumn   string    `json:"target_column"`
	DerivationType string    `json:"derivation_type"`
	Expression     *string   `json:"expression"`
	Context        *string   `json:"context"`
	Line           *int32    `json:"line"`
}

func (q *Queries) InsertColumnReference(ctx context.Context, arg InsertColumnReferenceParams) error {
	_, err := q.db.Exec(ctx, insertColumnReference,
		arg.ProjectID,
		arg.IndexRunID,
		arg.SourceColumn,
		arg.TargetColumn,
		arg.DerivationType,
		arg.Expression,
		arg.Context,
		arg.Line,
	)
	return err
}

const listColumnReferencesByIndexRun = `-- name: ListColumnReferencesByIndexRun :many
SELECT id, project_id, index_run_id, source_column, target_column, derivation_type, expression, context, line, created_at FROM column_references WHERE index_run_id = $1
`

func (q *Queries) ListColumnReferencesByIndexRun(ctx context.Context, indexRunID uuid.UUID) ([]ColumnReference, error) {
	rows, err := q.db.Query(ctx, listColumnReferencesByIndexRun, indexRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ColumnReference{}
	for rows.Next() {
		var i ColumnReference
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexRunID,
			&i.SourceColumn,
			&i.TargetColumn,
			&i.DerivationType,
			&i.Expression,
			&i.Context,
			&i.Line,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
