// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: edges.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countEdgesByProject = `-- name: CountEdgesByProject :one
SELECT count(*) FROM symbol_edges WHERE project_id = $1
`

func (q *Queries) CountEdgesByProject(ctx context.Context, projectID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEdgesByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSymbolEdge = `-- name: CreateSymbolEdge :one
INSERT INTO symbol_edges (project_id, source_id, target_id, edge_type)
VALUES ($1, $2, $3, $4)
ON CONFLICT (project_id, source_id, target_id, edge_type) DO NOTHING
RETURNING id, project_id, source_id, target_id, edge_type, metadata, created_at
`

type CreateSymbolEdgeParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	SourceID  uuid.UUID `json:"source_id"`
	TargetID  uuid.UUID `json:"target_id"`
	EdgeType  string    `json:"edge_type"`
}

func (q *Queries) CreateSymbolEdge(ctx context.Context, arg CreateSymbolEdgeParams) (SymbolEdge, error) {
	row := q.db.QueryRow(ctx, createSymbolEdge,
		arg.ProjectID,
		arg.SourceID,
		arg.TargetID,
		arg.EdgeType,
	)
	var i SymbolEdge
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.TargetID,
		&i.EdgeType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createSymbolEdgeWithMetadata = `-- name: CreateSymbolEdgeWithMetadata :one
INSERT INTO symbol_edges (project_id, source_id, target_id, edge_type, metadata)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (project_id, source_id, target_id, edge_type) DO UPDATE
SET metadata = EXCLUDED.metadata
RETURNING id, project_id, source_id, target_id, edge_type, metadata, created_at
`

type CreateSymbolEdgeWithMetadataParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	SourceID  uuid.UUID `json:"source_id"`
	TargetID  uuid.UUID `json:"target_id"`
	EdgeType  string    `json:"edge_type"`
	Metadata  []byte    `json:"metadata"`
}

func (q *Queries) CreateSymbolEdgeWithMetadata(ctx context.Context, arg CreateSymbolEdgeWithMetadataParams) (SymbolEdge, error) {
	row := q.db.QueryRow(ctx, createSymbolEdgeWithMetadata,
		arg.ProjectID,
		arg.SourceID,
		arg.TargetID,
		arg.EdgeType,
		arg.Metadata,
	)
	var i SymbolEdge
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.SourceID,
		&i.TargetID,
		&i.EdgeType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getIncomingEdges = `-- name: GetIncomingEdges :many
SELECT id, project_id, source_id, target_id, edge_type, metadata, created_at FROM symbol_edges WHERE target_id = $1
`

func (q *Queries) GetIncomingEdges(ctx context.Context, targetID uuid.UUID) ([]SymbolEdge, error) {
	rows, err := q.db.Query(ctx, getIncomingEdges, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolEdge{}
	for rows.Next() {
		var i SymbolEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.TargetID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOutgoingEdges = `-- name: GetOutgoingEdges :many
SELECT id, project_id, source_id, target_id, edge_type, metadata, created_at FROM symbol_edges WHERE source_id = $1
`

func (q *Queries) GetOutgoingEdges(ctx context.Context, sourceID uuid.UUID) ([]SymbolEdge, error) {
	rows, err := q.db.Query(ctx, getOutgoingEdges, sourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolEdge{}
	for rows.Next() {
		var i SymbolEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.TargetID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listColumnEdgesByProject = `-- name: ListColumnEdgesByProject :many
SELECT id, project_id, source_id, target_id, edge_type, metadata, created_at FROM symbol_edges
WHERE project_id = $1
  AND edge_type IN ('transforms_to', 'direct_copy', 'uses_column')
`

func (q *Queries) ListColumnEdgesByProject(ctx context.Context, projectID uuid.UUID) ([]SymbolEdge, error) {
	rows, err := q.db.Query(ctx, listColumnEdgesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolEdge{}
	for rows.Next() {
		var i SymbolEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.TargetID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesByProject = `-- name: ListEdgesByProject :many
SELECT id, project_id, source_id, target_id, edge_type, metadata, created_at FROM symbol_edges WHERE project_id = $1
`

func (q *Queries) ListEdgesByProject(ctx context.Context, projectID uuid.UUID) ([]SymbolEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolEdge{}
	for rows.Next() {
		var i SymbolEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.TargetID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEdgesByProjectCreatedSince = `-- name: ListEdgesByProjectCreatedSince :many
SELECT id, project_id, source_id, target_id, edge_type, metadata, created_at FROM symbol_edges WHERE project_id = $1 AND created_at >= $2
`

type ListEdgesByProjectCreatedSinceParams struct {
	ProjectID uuid.UUID `json:"project_id"`
	Since     time.Time `json:"since"`
}

func (q *Queries) ListEdgesByProjectCreatedSince(ctx context.Context, arg ListEdgesByProjectCreatedSinceParams) ([]SymbolEdge, error) {
	rows, err := q.db.Query(ctx, listEdgesByProjectCreatedSince, arg.ProjectID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SymbolEdge{}
	for rows.Next() {
		var i SymbolEdge
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.SourceID,
			&i.TargetID,
			&i.EdgeType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
