// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph_deletions.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const deleteGraphDeletionsByIndexRun = `-- name: DeleteGraphDeletionsByIndexRun :exec
DELETE FROM graph_deletions WHERE index_run_id = $1
`

func (q *Queries) DeleteGraphDeletionsByIndexRun(ctx context.Context, indexRunID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGraphDeletionsByIndexRun, indexRunID)
	return err
}

const listGraphDeletionsByIndexRun = `-- name: ListGraphDeletionsByIndexRun :many
SELECT id, index_run_id, project_id, node_id, node_type, created_at FROM graph_deletions WHERE index_run_id = $1
`

func (q *Queries) ListGraphDeletionsByIndexRun(ctx context.Context, indexRunID uuid.UUID) ([]GraphDeletion, error) {
	rows, err := q.db.Query(ctx, listGraphDeletionsByIndexRun, indexRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GraphDeletion{}
	for rows.Next() {
		var i GraphDeletion
		if err := rows.Scan(
			&i.ID,
			&i.IndexRunID,
			&i.ProjectID,
			&i.NodeID,
			&i.NodeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordGraphDeletion = `-- name: RecordGraphDeletion :exec
INSERT INTO graph_deletions (index_run_id, project_id, node_id, node_type)
VALUES ($1, $2, $3, $4)
`

type RecordGraphDeletionParams struct {
	IndexRunID uuid.UUID `json:"index_run_id"`
	ProjectID  uuid.UUID `json:"project_id"`
	NodeID     uuid.UUID `json:"node_id"`
	NodeType   string    `json:"node_type"`
}

func (q *Queries) RecordGraphDeletion(ctx context.Context, arg RecordGraphDeletionParams) error {
	_, err := q.db.Exec(ctx, recordGraphDeletion,
		arg.IndexRunID,
		arg.ProjectID,
		arg.NodeID,
		arg.NodeType,
	)
	return err
}
