// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	pgvector_go "github.com/pgvector/pgvector-go"
)

type ApiKey struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	KeyHash   string             `json:"key_hash"`
	Prefix    string             `json:"prefix"`
	Scopes    []string           `json:"scopes"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LastUsed  pgtype.Timestamptz `json:"last_used"`
	CreatedAt time.Time          `json:"created_at"`
}

type ColumnReference struct {
	ID             uuid.UUID `json:"id"`
	ProjectID      uuid.UUID `json:"project_id"`
	IndexRunID     uuid.UUID `json:"index_run_id"`
	SourceColumn   string    `json:"source_column"`
	TargetColumn   string    `json:"target_column"`
	DerivationType string    `json:"derivation_type"`
	Expression     *string   `json:"expression"`
	Context        *string   `json:"context"`
	Line           *int32    `json:"line"`
	CreatedAt      time.Time `json:"created_at"`
}

type File struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	SourceID      uuid.UUID          `json:"source_id"`
	Path          string             `json:"path"`
	Language      string             `json:"language"`
	SizeBytes     int64              `json:"size_bytes"`
	Hash          string             `json:"hash"`
	LastIndexedAt pgtype.Timestamptz `json:"last_indexed_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
}

type GraphDeletion struct {
	ID         uuid.UUID `json:"id"`
	IndexRunID uuid.UUID `json:"index_run_id"`
	ProjectID  uuid.UUID `json:"project_id"`
	NodeID     uuid.UUID `json:"node_id"`
	NodeType   string    `json:"node_type"`
	CreatedAt  time.Time `json:"created_at"`
}

type IndexRun struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      uuid.UUID          `json:"project_id"`
	SourceID       pgtype.UUID        `json:"source_id"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	FilesProcessed int32              `json:"files_processed"`
	SymbolsFound   int32              `json:"symbols_found"`
	EdgesFound     int32              `json:"edges_found"`
	ErrorMessage   *string            `json:"error_message"`
	Metadata       []byte             `json:"metadata"`
	CreatedAt      time.Time          `json:"created_at"`
}

type Membership struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	UserSub   string    `json:"user_sub"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Project struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description *string     `json:"description"`
	Settings    []byte      `json:"settings"`
	CreatedBy   pgtype.UUID `json:"created_by"`
	CreatedAt   time.Time   `json:"created_at"`
	UpdatedAt   time.Time   `json:"updated_at"`
	TenantID    uuid.UUID   `json:"tenant_id"`
}

type ProjectAnalytic struct {
	ID         uuid.UUID `json:"id"`
	ProjectID  uuid.UUID `json:"project_id"`
	Scope      string    `json:"scope"`
	ScopeID    string    `json:"scope_id"`
	Analytics  []byte    `json:"analytics"`
	Summary    *string   `json:"summary"`
	ComputedAt time.Time `json:"computed_at"`
}

type ProjectMember struct {
	ProjectID uuid.UUID `json:"project_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type RawReference struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	IndexRunID    uuid.UUID `json:"index_run_id"`
	FileID        uuid.UUID `json:"file_id"`
	FromSymbol    string    `json:"from_symbol"`
	ToName        string    `json:"to_name"`
	ToQualified   string    `json:"to_qualified"`
	ReferenceType string    `json:"reference_type"`
	Confidence    float64   `json:"confidence"`
	Line          *int32    `json:"line"`
	Language      string    `json:"language"`
	CreatedAt     time.Time `json:"created_at"`
}

type Source struct {
	ID            uuid.UUID          `json:"id"`
	ProjectID     uuid.UUID          `json:"project_id"`
	Name          string             `json:"name"`
	SourceType    string             `json:"source_type"`
	ConnectionUri *string            `json:"connection_uri"`
	Config        []byte             `json:"config"`
	LastSyncedAt  pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt     time.Time          `json:"created_at"`
	UpdatedAt     time.Time          `json:"updated_at"`
	LastCommitSha *string            `json:"last_commit_sha"`
}

type Symbol struct {
	ID            uuid.UUID `json:"id"`
	ProjectID     uuid.UUID `json:"project_id"`
	FileID        uuid.UUID `json:"file_id"`
	Name          string    `json:"name"`
	QualifiedName string    `json:"qualified_name"`
	Kind          string    `json:"kind"`
	Language      string    `json:"language"`
	StartLine     int32     `json:"start_line"`
	EndLine       int32     `json:"end_line"`
	StartCol      *int32    `json:"start_col"`
	EndCol        *int32    `json:"end_col"`
	Signature     *string   `json:"signature"`
	DocComment    *string   `json:"doc_comment"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type SymbolEdge struct {
	ID        uuid.UUID `json:"id"`
	ProjectID uuid.UUID `json:"project_id"`
	SourceID  uuid.UUID `json:"source_id"`
	TargetID  uuid.UUID `json:"target_id"`
	EdgeType  string    `json:"edge_type"`
	Metadata  []byte    `json:"metadata"`
	CreatedAt time.Time `json:"created_at"`
}

type SymbolEmbedding struct {
	ID        uuid.UUID          `json:"id"`
	SymbolID  uuid.UUID          `json:"symbol_id"`
	Embedding pgvector_go.Vector `json:"embedding"`
	Model     string             `json:"model"`
	CreatedAt time.Time          `json:"created_at"`
}

type Tenant struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
	Settings  []byte    `json:"settings"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
	AvatarUrl *string   `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Sub       *string   `json:"sub"`
}
