// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_references.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const deleteRawReferencesByIndexRun = `-- name: DeleteRawReferencesByIndexRun :exec
DELETE FROM raw_references WHERE index_run_id = $1
`

func (q *Queries) DeleteRawReferencesByIndexRun(ctx context.Context, indexRunID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRawReferencesByIndexRun, indexRunID)
	return err
}

const insertRawReference = `-- name: InsertRawReference :exec
INSERT INTO raw_references (project_id, index_run_id, file_id, from_symbol, to_name, to_qualified, reference_type, confidence, line, language)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertRawReferenceParams struct {
	ProjectID     uuid.UUID `json:"project_id"`
	IndexRunID    uuid.UUID `json:"index_run_id"`
	FileID        uuid.UUID `json:"file_id"`
	FromSymbol    string    `json:"from_symbol"`
	ToName        string    `json:"to_name"`
	ToQualified   string    `json:"to_qualified"`
	ReferenceType string    `json:"reference_type"`
	Confidence    float64   `json:"confidence"`
	Line          *int32    `json:"line"`
	Language      string    `json:"language"`
}

func (q *Queries) InsertRawReference(ctx context.Context, arg InsertRawReferenceParams) error {
	_, err := q.db.Exec(ctx, insertRawReference,
		arg.ProjectID,
		arg.IndexRunID,
		arg.FileID,
		arg.FromSymbol,
		arg.ToName,
		arg.ToQualified,
		arg.ReferenceType,
		arg.Confidence,
		arg.Line,
		arg.Language,
	)
	return err
}

const listRawReferencesByIndexRun = `-- name: ListRawReferencesByIndexRun :many
SELECT id, project_id, index_run_id, file_id, from_symbol, to_name, to_qualified, reference_type, confidence, line, language, created_at FROM raw_references WHERE index_run_id = $1
`

func (q *Queries) ListRawReferencesByIndexRun(ctx context.Context, indexRunID uuid.UUID) ([]RawReference, error) {
	rows, err := q.db.Query(ctx, listRawReferencesByIndexRun, indexRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawReference{}
	for rows.Next() {
		var i RawReference
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IndexRunID,
			&i.FileID,
			&i.FromSymbol,
			&i.ToName,
			&i.ToQualified,
			&i.ReferenceType,
			&i.Confidence,
			&i.Line,
			&i.Language,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
